[frontend研修] Rails7に対応
pepabo/training pull request #22
Opened 2024-05-28 01:09 UTC by nacal

2024-05-28 08:39 UTC, piyoppi requested changes

2024-05-28 08:39 UTC, piyoppi commented on frontend-training/docs/ch16/README.md
> +現在時点での最新版である第７版の Rails チュートリアルでは、前述の`webpacker`を利用していません。第７版の教材を基に作成した Rails アプリケーションに対してこの研修を進めるためには`webpacker`gem を剥がす作業は不要になるので、17 章の内容に入る前に、「付録 4 Rails7 での準備」に進んでください。
付録4 はRails6に対しての言及があるようなので、ここでAppendixについて案内する必要はなさそうです

2024-05-28 08:39 UTC, piyoppi commented on frontend-training/docs/ch16/README.md
>  これらを機械的に行ってブラウザで実行できる一つの巨大なファイルを生成する（トランスパイリング＋バンドリング）ことを行ってくれるのが、（名前は聞いたことあるかもしれません） [webpack](https://webpack.js.org/) です。そして webpack 自体は JavaScript 製のツールですが、これを Rails で扱えるようにしたのが `webpacker` gem で
Webpackerのことはもう触れなくてもいいかもとおもいました(これから研修を受ける人が気にする必要がなさそうなため)

```suggestion
これらを機械的に行ってブラウザで実行できる一つの巨大なファイルを生成する（トランスパイリング＋バンドリング）ことを行ってくれるのが、（名前は聞いたことあるかもしれません） [webpack](https://webpack.js.org/) です。
```

2024-05-28 09:40 UTC, nacal commented on frontend-training/docs/ch16/README.md
> +現在時点での最新版である第７版の Rails チュートリアルでは、前述の`webpacker`を利用していません。第７版の教材を基に作成した Rails アプリケーションに対してこの研修を進めるためには`webpacker`gem を剥がす作業は不要になるので、17 章の内容に入る前に、「付録 4 Rails7 での準備」に進んでください。
前回のPRの差分が入っちゃってました！消しました！

2024-05-29 00:51 UTC, piyoppi approved these changes
対応ありがとうございました。よさそうです

2024-05-29 01:50 UTC, merged